---
framework: mocha
nodeVersion: 14.17.2
preRun:
     command:
        - npm install
preMerge:
  pattern:
    - "./test/*.js"
postMerge:
  pattern:
    - "./test/*.js"
postRun:
     command:
        - node --version
version: 1.0
